### ISSUE TITLE
table as part of the heading?

### ISSUE THREAD

**Issue by lmaylein** [hcayless/P3-processing#4]
The table is part of the heading:

https://github.com/hcayless/P3-processing/blob/2a591fbe215816d5d8272209c47aa0e2549c8861/articles/ClaytorSmithWarga_FourPoll_TaxReceiptsTrial-2.xml#L168

Shouldn't `<table>` be outside `<head>`?

**Comment by hcayless** [comment]
I would argue that the papyrological info is properly part of the header, but I can change it if that's desirable. @jcowey what do you think?

**Comment by jcowey** [comment]
I failed to put `#editionHeader` at the appropriate place in the text. Have done so and committed:
ClaytorSmithWarga_FourPoll_TaxReceiptsTrial-3.docx, which presents: 
```
            <div type="section">
               <head>Table 1. Poll Tax Receipts on Papyrus, 30 BCE – 37 CE<note place="foot" xml:id="ftn9" n="9">
                     <p style="text-align:; "> The two orders to issue poll-tax receipts, recently (re)edited by Hagedorn, should be considered together with these receipts: Hagedorn 2013 (n. 7).</p>
                  </note>
               </head>
               <table>
```
at https://github.com/hcayless/P3-processing/blob/main/articles/ClaytorSmithWarga_FourPoll_TaxReceiptsTrial-3.xml#L67-L72

instead of 
```
            <table>
               <head>Table 1. Poll Tax Receipts on Papyrus, 30 BCE – 37 CE<note place="foot" xml:id="ftn10" n="9">
                     <p> The two orders to issue poll-tax receipts, recently (re)edited by Hagedorn, should be considered together with these receipts: Hagedorn 2013 (n. 7).</p>
                  </note>
               </head>
```
at https://github.com/hcayless/P3-processing/blob/main/articles/ClaytorSmithWarga_FourPoll_TaxReceiptsTrial-2.xml#L67-L71

**Comment by jcowey** [comment]
I am happy with this now.
https://github.com/hcayless/P3-processing/blob/main/articles/ClaytorSmithWarga_FourPoll_TaxReceiptsTrial-3.xml#L67-L72

**Comment by GusRiva** [comment]
I think the table outside the `<head>` as in the corrected version is better. We don't need a `<p>` inside the  `<head>`, it can contain a text node (and that is probably better for the visualization).

**Comment by jcowey** [comment]
Tables will only have headers (at top and not bottom)

**Comment by lmaylein** [comment]
I'm afraid I still don't get it. In this case, "Table 1. Poll Tax Receipts on Papyrus, 30 BCE – 37 CE" is the heading of the table, isn't it? Therefore, in my opinion, this head tag should be within the table tag. But what is the heading of the section here (section tag directly above the table)? Does this section not have a heading?

**Comment by hcayless** [comment]
It's not a section--marking it that way in the Word doc was an error. It's just a table with a caption. As I noted to James yesterday, the current TEI Stylesheets functionality is to make a table with a caption above it into 
```xml
<table>
  <head>...</head>
  <row>...etc</rom>
</table>
```
But if the caption is below the table, it will be output as a `<figure>` containing a table with a caption (`<head>`) following the table, because tables can only have headings at the top. We decided the journal style guide could specify that table captions always occur before the tables. @GusRiva, the `<p>` is in a `<note>`. This is an optional convention as far as TEI is concerned, but we can't rule out multi-paragraph notes so probably best to leave it.
